// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212151631_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Static.Ability", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("API.Models.Static.BaseStats", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("PokemonId");

                    b.ToTable("BaseStats");
                });

            modelBuilder.Entity("API.Models.Static.DamageClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DamageClass");
                });

            modelBuilder.Entity("API.Models.Static.Gender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("API.Models.Static.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("API.Models.Static.Move", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("integer");

                    b.Property<int>("DamageClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MoveEffectChance")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveEffectId")
                        .HasColumnType("integer");

                    b.Property<int?>("PP")
                        .HasColumnType("integer")
                        .HasColumnName("pp");

                    b.Property<int>("PkmnTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Power")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DamageClassId");

                    b.HasIndex("MoveEffectId");

                    b.HasIndex("PkmnTypeId");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("API.Models.Static.MoveEffect", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MoveEffect");
                });

            modelBuilder.Entity("API.Models.Static.Nature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("AttackMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("DefenseMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SpecialAttackMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("SpecialDefenseMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Nature");
                });

            modelBuilder.Entity("API.Models.Static.PkmnType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PkmnType");
                });

            modelBuilder.Entity("API.Models.Static.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("API.Models.Static.PokemonAbility", b =>
                {
                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("AbilityId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonAbility");
                });

            modelBuilder.Entity("API.Models.Static.PokemonGender", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("GenderId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonGender");
                });

            modelBuilder.Entity("API.Models.Static.PokemonMove", b =>
                {
                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("MoveId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonMove");
                });

            modelBuilder.Entity("API.Models.Static.PokemonPkmnType", b =>
                {
                    b.Property<int>("PkmnTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("PkmnTypeId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonPkmnType");
                });

            modelBuilder.Entity("API.Models.User.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "test1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d906ac19-07fb-4628-9b04-f2d4fa2f2256",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f24ce601-d425-4f54-a193-671d50dfa851",
                            TwoFactorEnabled = false,
                            UserName = "TestUser1"
                        },
                        new
                        {
                            Id = "test2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a57d2c7-5210-4b55-abfc-5c52f9d11e3d",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf572389-3493-4489-b9d1-0684be661e73",
                            TwoFactorEnabled = false,
                            UserName = "TestUser2"
                        });
                });

            modelBuilder.Entity("API.Models.User.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("API.Models.User.UserPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("AttackEV")
                        .HasColumnType("integer");

                    b.Property<int>("AttackIV")
                        .HasColumnType("integer");

                    b.Property<int>("DefenseEV")
                        .HasColumnType("integer");

                    b.Property<int>("DefenseIV")
                        .HasColumnType("integer");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<int>("HPEV")
                        .HasColumnType("integer");

                    b.Property<int>("HPIV")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("Move1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move3Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move4Id")
                        .HasColumnType("integer");

                    b.Property<int>("NatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Shiny")
                        .HasColumnType("boolean");

                    b.Property<int>("SpecialAttackEV")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialAttackIV")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialDefenseEV")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialDefenseIV")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedEV")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedIV")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamSlot")
                        .HasColumnType("integer");

                    b.Property<int>("TeraPkmnTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Move1Id");

                    b.HasIndex("Move2Id");

                    b.HasIndex("Move3Id");

                    b.HasIndex("Move4Id");

                    b.HasIndex("NatureId");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeraPkmnTypeId");

                    b.ToTable("UserPokemon");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "715ea566-da75-4eb2-8ae9-a9bc4fcce567",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "8cb44501-4b2b-4d84-8478-dd7bfe361607",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Models.Static.BaseStats", b =>
                {
                    b.HasOne("API.Models.Static.Pokemon", "Pokemon")
                        .WithOne("BaseStats")
                        .HasForeignKey("API.Models.Static.BaseStats", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("API.Models.Static.Move", b =>
                {
                    b.HasOne("API.Models.Static.DamageClass", "DamageClass")
                        .WithMany()
                        .HasForeignKey("DamageClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.MoveEffect", "MoveEffect")
                        .WithMany("Moves")
                        .HasForeignKey("MoveEffectId");

                    b.HasOne("API.Models.Static.PkmnType", "PkmnType")
                        .WithMany()
                        .HasForeignKey("PkmnTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageClass");

                    b.Navigation("MoveEffect");

                    b.Navigation("PkmnType");
                });

            modelBuilder.Entity("API.Models.Static.PokemonAbility", b =>
                {
                    b.HasOne("API.Models.Static.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.Pokemon", "Pokemon")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("API.Models.Static.PokemonGender", b =>
                {
                    b.HasOne("API.Models.Static.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("API.Models.Static.PokemonMove", b =>
                {
                    b.HasOne("API.Models.Static.Move", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.Pokemon", "Pokemon")
                        .WithMany("PokemonMoves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("API.Models.Static.PokemonPkmnType", b =>
                {
                    b.HasOne("API.Models.Static.PkmnType", "PkmnType")
                        .WithMany()
                        .HasForeignKey("PkmnTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.Pokemon", "Pokemon")
                        .WithMany("PokemonPkmnTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PkmnType");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("API.Models.User.Team", b =>
                {
                    b.HasOne("API.Models.User.AppUser", "AppUser")
                        .WithMany("Teams")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Models.User.UserPokemon", b =>
                {
                    b.HasOne("API.Models.Static.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId");

                    b.HasOne("API.Models.Static.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("API.Models.Static.Move", "Move1")
                        .WithMany()
                        .HasForeignKey("Move1Id");

                    b.HasOne("API.Models.Static.Move", "Move2")
                        .WithMany()
                        .HasForeignKey("Move2Id");

                    b.HasOne("API.Models.Static.Move", "Move3")
                        .WithMany()
                        .HasForeignKey("Move3Id");

                    b.HasOne("API.Models.Static.Move", "Move4")
                        .WithMany()
                        .HasForeignKey("Move4Id");

                    b.HasOne("API.Models.Static.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId");

                    b.HasOne("API.Models.User.Team", "Team")
                        .WithMany("UserPokemon")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Static.PkmnType", "TeraPkmnType")
                        .WithMany()
                        .HasForeignKey("TeraPkmnTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Gender");

                    b.Navigation("Item");

                    b.Navigation("Move1");

                    b.Navigation("Move2");

                    b.Navigation("Move3");

                    b.Navigation("Move4");

                    b.Navigation("Nature");

                    b.Navigation("Pokemon");

                    b.Navigation("Team");

                    b.Navigation("TeraPkmnType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("API.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("API.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("API.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.Static.MoveEffect", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("API.Models.Static.Pokemon", b =>
                {
                    b.Navigation("BaseStats")
                        .IsRequired();

                    b.Navigation("PokemonAbilities");

                    b.Navigation("PokemonMoves");

                    b.Navigation("PokemonPkmnTypes");
                });

            modelBuilder.Entity("API.Models.User.AppUser", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("API.Models.User.Team", b =>
                {
                    b.Navigation("UserPokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
